### ISSUE TITLE
I don't see a cheat

### ISSUE THREAD

**Issue by AleksandrPavlik** [CasualX/apexdream#40]
Hi! I compiled the cheat with the cargo build, but I still can't see the cheat itself. maybe I'm doing something wrong? 
![Screenshot 2023-03-26 080824](https://user-images.githubusercontent.com/120610440/227784958-b0714089-ad5d-4ef1-b5cb-80c448fdf2c7.png)

**Comment by CasualX** [comment]
You can find the binary in `target\debug\examples\apexdream-win32.exe` but that one does not attempt to bypass EAC and simply does not work with EAC.
