### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by bcreativeproduction** [CasualX/apexdream#41]
Error reading gamedata.ini, also can't seem to get apex dumper to work, would you be able to talk to me on discord and help me? I'm really struggling and just want to try it D: 
Cuffy#5022

**Comment by bcreativeproduction** [comment]
Not able to help me with why I keep getting error reading gamedata.ini?

**Comment by CasualX** [comment]
No sry, this is not intended as an easy to use cheat for people who don't know how to code.
