### ISSUE TITLE
Hello sir! litle help me

### ISSUE THREAD

**Issue by Puccu01** [CasualX/apexdream#43]
I did everything correctly, the offset is also up to date, but during the Cargo test, it keeps showing this error.
The Cargo build --release completes successfully, but there is no .exe file.
![Képernyőkép 2023-04-25 110222](https://user-images.githubusercontent.com/103877793/234231317-85b09dcc-dcc2-4135-8920-9e2e26dae314.png)
![build 111312](https://user-images.githubusercontent.com/103877793/234231401-3fdf41f0-3156-4ede-a844-7051f5296ef8.png)
I hope I did not tire you with my ignorance. Have a nice day!

**Comment by narucalo** [comment]
Give up and move on dude. This project is a bunch of rust code from different games pasted together with missing rust library depencies.
