### ISSUE TITLE
how to use it?

### ISSUE THREAD

**Issue by resphinas** [CasualX/apexdream#53]
how to use it?

**Comment by CasualX** [comment]
I have not played apex in 6 months now, I cannot help you sry.

**Comment by resphinas** [comment]
why don’t you play it,isn't it fun for you anymore?




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年9月27日(星期三) 凌晨5:59
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [CasualX/apexdream] how to use it? (Issue #53)





 
I have not played apex in 6 months now, I cannot help you sry.

**Comment by resphinas** [comment]
I would like to ask which knowledge I need to learn if I want to be a successful hacker of apex. Thank you very much.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CasualX/apexdream"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月27日(星期三) 凌晨5:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [CasualX/apexdream] how to use it? (Issue #53)





 
I have not played apex in 6 months now, I cannot help you sry.

**Comment by xiopt** [comment]
Starting season 18 the entity_highlight was removed from dump table and highlight function needs rework. Interested on how would this cleanly be approached in this context..
